{% set name = "pineappl" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/pineappl/archive/v{{ version }}.tar.gz
  sha256: 4bbd3df56e71c7ab7f0e0bd167ec77b52fe1ebdce004cf2a9aeca294f6e42bb0

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - python
    - pip
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
  host:
    - pkg-config
    - openssl
    - python
    - pip
    - maturin
  run:
    - python
    - numpy
    - pkgconfig

test:
  imports:
    - pineappl

about:
  home: https://github.com/N3PDF/pineappl
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: PineAPPL is not an extension of APPLgrid.

extra:
  recipe-maintainers:
    - scarrazza
    - cschwan
